services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data      # your PDFs live here
      - ./backend/vectordb:/app/vectordb
    environment:
      PDF_DATA_DIR: /app/data
      DB_PERSIST_DIR: /app/vectordb
      PYTHONUNBUFFERED: "1"
    networks:
      - riskai_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      # if you update your front-end to honor NEXT_PUBLIC_API_URL:
      # NEXT_PUBLIC_API_URL: http://backend:8000
    networks:
      - riskai_network

networks:
  riskai_network:
    driver: bridge

